export const DEFAULT_COLLECTION = {
  info: {
    _postman_id: "e92f9759-e33e-4da0-84a6-cba87ee6958d",
    name: "LIS Direct Reporting API - QA Core",
    schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    description: "Enterprise QA Testing Suite for LIS Direct Reporting API with HMAC Authentication and Bulk Job Processing."
  },
  variable: [
    { key: "baseUrl", value: "http://localhost:5000" },
    { key: "language", value: "en", description: "Response language: 'en' for English (default), 'es' for Spanish" },
    { key: "reportingToken", value: "" },
    { key: "reportingRefreshToken", value: "" },
    { key: "adminToken", value: "" },
    { key: "adminRefreshToken", value: "" },
    { key: "reportId", value: "" },
    { key: "businessId", value: "" },
    { key: "hmacAppKey", value: "DEMO_APP_KEY_8812", description: "AppKey from Create Business → data.apiClient.appKey" },
    { key: "hmacSecret", value: "c2VjcmV0X2tleV9kZW1vXzEyMzQ1Njc4OTA=", description: "Secret from Create Business (Base64)" },
    { key: "labUserId", value: "" },
    { key: "activationToken", value: "" },
    { key: "labUserToken", value: "" },
    { key: "labUserRefreshToken", value: "" },
    { key: "userAuthToken", value: "" },
    { key: "userAuthRefreshToken", value: "" },
    { key: "bulkJobId", value: "61a3b75c-b788-4173-aa07-a203ba21bbe7" }
  ],
  item: [
    {
      id: "folder-external-apis",
      name: "🔌 External APIs",
      description: "HMAC-authenticated endpoints for external integrations. All requests require X-App-Key, X-Timestamp, X-Nonce, and X-Signature headers generated by the pre-request script.",
      item: [
        {
          id: "req-1",
          name: "ResultFileUpload",
          request: {
            method: "POST",
            header: [
              { key: "X-App-Key", value: "{{hmacAppKey}}", description: "HMAC client AppKey" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}", description: "Unix timestamp in seconds - set by pre-request script" },
              { key: "X-Nonce", value: "{{hmac_nonce}}", description: "One-time UUID - set by pre-request script" },
              { key: "X-Signature", value: "{{hmac_signature}}", description: "Base64 HMAC-SHA256 signature - set by pre-request script" }
            ],
            body: {
              mode: "formdata",
              formdata: [
                { key: "serviceType", value: "PGX", type: "text" },
                { key: "CNVFile", type: "file", description: "CNV result file", src: "/D:/MyFolder/Preni/Docs/DirectReportingAPI/TestData/Demo/St_Comp_CNV_003.xlsx" },
                { key: "SNPResultFile", type: "file", description: "SNP result file", src: "/D:/MyFolder/Preni/Docs/DirectReportingAPI/TestData/Demo/St_Comp_SNP_003.xlsx" },
                { key: "SLC6A4File", type: "file", description: "SLC6A4 result file (Optional)", value: null, disabled: true }
              ]
            },
            url: {
              raw: "{{baseUrl}}/api/v1/resultfileupload",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "resultfileupload"]
            },
            description: "Upload CNV and SNP result files for a specimen. Uses HMAC auth with empty body hash (multipart body is not signed)."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "",
                  "// FIX: Dynamically read the JSON body from the request",
                  "let rawBody = '';",
                  "if (pm.request.body && pm.request.body.mode === 'raw') {",
                  "    rawBody = pm.request.body.raw;",
                  "} else if (pm.request.headers.get('Content-Type')?.includes('multipart/form-data')) {",
                  "    rawBody = '';",
                  "}",
                  "",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 200', () => pm.response.to.have.status(200));",
                  "pm.test('Success true', () => pm.expect(pm.response.json().success).to.be.true);"
                ]
              }
            }
          ]
        },
        {
          id: "req-2",
          name: "Reporting",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}", description: "HMAC client AppKey" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}", description: "Unix timestamp (seconds) - set by pre-request script" },
              { key: "X-Nonce", value: "{{hmac_nonce}}", description: "Random nonce - set by pre-request script" },
              { key: "X-Signature", value: "{{hmac_signature}}", description: "Base64 HMAC-SHA256 signature - set by pre-request script" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({
                serviceType: 1,
                panelName: "Emgenex_Panel_14",
                reportTitle: "Comprehensive PGx Panel",
                specimenData: [
                  {
                    patientProfile: {
                      firstName: "Test",
                      lastName: "Patent1",
                      dob: "2000-01-01",
                      gender: "O",
                      mrn: "TP22222"
                    },
                    specimenProfile: {
                      specimenId: "DR08052601S",
                      collectionMethod: { code: "733104004", label: "Buccal swab", typeCodeSystem: "SNOMED" },
                      collectedDate: "2026-05-02T20:30:00",
                      receivedDate: "2026-05-02T20:30:00",
                      reportedDate: "2026-05-03T11:30:00"
                    },
                    providerProfile: {
                      fullName: "Pamelo Alex",
                      title: "Dr.",
                      npi: "9898989898",
                      facility: "Angel's Clinic",
                      address: { street1: "1 Sweet Lane", street2: "Suite T", city: "Downtown", state: "NE", country: "USA", zip: "00045" }
                    }
                  }
                ],
                labProfile: {
                  logo: "https://azdevwh.brandoptics.com/silvermed.png",
                  name: "Silver Medical Dx Lab",
                  phone: "121-111-1111",
                  fax: "121-111-2222",
                  email: "contactus@silverDxlabs.com",
                  labDirector: "Peter Parker",
                  timeZone: "ET",
                  timeZoneOffset: "-05:00",
                  clia: { isClia: true, cliaNumber: "12PP89F56" },
                  address: { street1: "Builg#199 Happy Land", street2: "", city: "Bellevue", state: "NY", country: "USA", zip: "00034" }
                }
              }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/reporting",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "reporting"]
            },
            description: "Enqueues a bulk report generation job. Returns 202 Accepted with a jobId. Use 'Poll Bulk Job Status' to track progress. The jobId is auto-saved to {{bulkJobId}} collection variable."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "",
                  "let rawBody = '';",
                  "if (pm.request.body && pm.request.body.mode === 'raw') {",
                  "    rawBody = pm.request.body.raw;",
                  "} else if (pm.request.headers.get('Content-Type')?.includes('multipart/form-data')) {",
                  "    rawBody = '';",
                  "}",
                  "",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 202', () => pm.response.to.have.status(202));",
                  "pm.test('JobId present', function() {",
                  "  const json = pm.response.json();",
                  "  pm.expect(json.jobId).to.be.a('string');",
                  "  pm.collectionVariables.set('bulkJobId', json.jobId);",
                  "  console.log('Bulk job queued:', json.jobId);",
                  "});"
                ]
              }
            }
          ]
        },
        {
          id: "req-3",
          name: "ReportingBulk",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}", description: "HMAC client AppKey" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}", description: "Unix timestamp (seconds) - set by pre-request script" },
              { key: "X-Nonce", value: "{{hmac_nonce}}", description: "Random nonce - set by pre-request script" },
              { key: "X-Signature", value: "{{hmac_signature}}", description: "Base64 HMAC-SHA256 signature - set by pre-request script" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({
                serviceType: 1,
                panelName: "Emgenex_Panel_14",
                reportTitle: "Comprehensive PGx Panel",
                specimenData: [
                  {
                    patientProfile: { firstName: "Test", lastName: "Patient2", dob: "2004-04-04", gender: "M", mrn: "TP11111" },
                    specimenProfile: { specimenId: "DR08052602S", collectionMethod: { code: "733104004", label: "Buccal swab", typeCodeSystem: "SNOMED" }, collectedDate: "2026-04-22T18:30:00", receivedDate: "2026-04-22T18:30:00", reportedDate: "2026-04-23T04:30:00" },
                    providerProfile: { fullName: "Freddy Gregory", title: "Dr.", npi: "1234568909", facility: "Medicare Facility", address: { street1: "#4, Medicare Facility", street2: "buldg #T", city: "Downtown", state: "NE", country: "USA", zip: "00001" } }
                  },
                  {
                    patientProfile: { firstName: "Test", lastName: "Patient3", dob: "2005-05-05", gender: "F", mrn: "TP22222" },
                    specimenProfile: { specimenId: "DR08052603S", collectionMethod: { code: "733104004", label: "Buccal swab", typeCodeSystem: "SNOMED" }, collectedDate: "2026-04-20T18:30:00", receivedDate: "2026-04-20T18:30:00", reportedDate: "2026-04-21T12:30:00" },
                    providerProfile: { fullName: "Michelle Green", title: "Dr.", npi: "3895384340", facility: "Greesn Clinic", address: { street1: "1 Sweet Lane", street2: "Suite T", city: "Downtown", state: "NE", country: "USA", zip: "00001" } }
                  }
                ],
                labProfile: {
                  logo: "https://azdevwh.brandoptics.com/silvermed.png",
                  name: "Silver Medical Lab",
                  phone: "111-111-1111",
                  fax: "111-222-2222",
                  email: "director@silverlabs.com",
                  labDirector: "Mike Gregory",
                  timeZone: "CT",
                  timeZoneOffset: "-06:00",
                  clia: { isClia: true, cliaNumber: "9999999999" },
                  address: { street1: "Blgng#2, Park Avenue Road", street2: "", city: "Midtown", state: "NY", country: "USA", zip: "00004" }
                }
              }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/reporting",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "reporting"]
            },
            description: "Enqueues a bulk report generation job for multiple specimens. Returns 202 Accepted with jobId."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "",
                  "let rawBody = '';",
                  "if (pm.request.body && pm.request.body.mode === 'raw') {",
                  "    rawBody = pm.request.body.raw;",
                  "} else if (pm.request.headers.get('Content-Type')?.includes('multipart/form-data')) {",
                  "    rawBody = '';",
                  "}",
                  "",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 202', () => pm.response.to.have.status(202));",
                  "pm.test('JobId present', function() {",
                  "  const json = pm.response.json();",
                  "  pm.expect(json.jobId).to.be.a('string');",
                  "  pm.collectionVariables.set('bulkJobId', json.jobId);",
                  "  console.log('Bulk job queued:', json.jobId);",
                  "});"
                ]
              }
            }
          ]
        },
        {
          id: "req-4",
          name: "AddCurrentMedications",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}" },
              { key: "X-Nonce", value: "{{hmac_nonce}}" },
              { key: "X-Signature", value: "{{hmac_signature}}" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({
                SpecimenId: "DR08052601",
                ShowMatchingDrugs: false,
                CurrentMedications: [
                  { DrugName: "Cevimeline", DosageForm: "Tablet", Strength: { Unit: "mg", Number: 500 } },
                  { DrugName: "Aripiprazole", DosageForm: "Tablet", Strength: { Unit: "mg/l", Number: 10 } },
                  { DrugName: "Lorazepam", DosageForm: "Tablet", Strength: { Unit: "mg/l", Number: 3 } }
                ],
                ModelName: "NewDrugAdded",
                Reason: "Changed because of high risk factors",
                Comments: "Medications added"
              }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/medication/addcurrentmedications",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "medication", "addcurrentmedications"]
            },
            description: "Retrieves current medications for a patient by specimenId and externalId."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "",
                  "let rawBody = '';",
                  "if (pm.request.body && pm.request.body.mode === 'raw') {",
                  "    rawBody = pm.request.body.raw;",
                  "} else if (pm.request.headers.get('Content-Type')?.includes('multipart/form-data')) {",
                  "    rawBody = '';",
                  "}",
                  "",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 200, 400 or 404', () => pm.expect([200, 400, 404]).to.include(pm.response.code));"
                ]
              }
            }
          ]
        },
        {
          id: "req-5",
          name: "CheckNewResults",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}" },
              { key: "X-Nonce", value: "{{hmac_nonce}}" },
              { key: "X-Signature", value: "{{hmac_signature}}" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({ serviceId: 1 }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/reports/checknewresults",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "reports", "checknewresults"]
            },
            description: "Check whether new results are available for the given specimen IDs."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "let rawBody     = pm.request.body && pm.request.body.mode === 'raw' ? pm.request.body.raw : '';",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 200', () => pm.response.to.have.status(200));",
                  "pm.test('Success true', () => pm.expect(pm.response.json().success).to.be.true);"
                ]
              }
            }
          ]
        },
        {
          id: "req-6",
          name: "GetJobStatus",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}" },
              { key: "X-Nonce", value: "{{hmac_nonce}}" },
              { key: "X-Signature", value: "{{hmac_signature}}" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({ bulkJobId: "{{bulkJobId}}" }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/reporting/bulk/status",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "reporting", "bulk", "status"]
            },
            description: "Check progress status of a queued bulk report job using bulkJobId."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "let rawBody     = pm.request.body && pm.request.body.mode === 'raw' ? pm.request.body.raw : '';",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 200', () => pm.response.to.have.status(200));",
                  "pm.test('Success true', () => pm.expect(pm.response.json().success).to.be.true);"
                ]
              }
            }
          ]
        },
        {
          id: "req-7",
          name: "GetPendingRegeneration",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}" },
              { key: "X-Nonce", value: "{{hmac_nonce}}" },
              { key: "X-Signature", value: "{{hmac_signature}}" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({ serviceId: 1 }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/reports/getpendingregeneration",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "reports", "getpendingregeneration"]
            },
            description: "Returns all reports flagged as pending regeneration."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "let rawBody     = pm.request.body && pm.request.body.mode === 'raw' ? pm.request.body.raw : '';",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 200', () => pm.response.to.have.status(200));",
                  "pm.test('Success true', () => pm.expect(pm.response.json().success).to.be.true);"
                ]
              }
            }
          ]
        },
        {
          id: "req-8",
          name: "GetReports",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}" },
              { key: "X-Nonce", value: "{{hmac_nonce}}" },
              { key: "X-Signature", value: "{{hmac_signature}}" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({ specimenId: "DR08052601S" }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/reports/getreports",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "reports", "getreports"]
            },
            description: "Returns a filtered, paginated list of reports."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "let rawBody     = pm.request.body && pm.request.body.mode === 'raw' ? pm.request.body.raw : '';",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 200', () => pm.response.to.have.status(200));",
                  "pm.test('Success true', () => pm.expect(pm.response.json().success).to.be.true);",
                  "pm.test('Data is array', () => pm.expect(pm.response.json().data).to.be.an('array'));"
                ]
              }
            }
          ]
        },
        {
          id: "req-9",
          name: "DownloadPDFReport",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}" },
              { key: "X-Nonce", value: "{{hmac_nonce}}" },
              { key: "X-Signature", value: "{{hmac_signature}}" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({ specimenId: "DR08052601S" }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/reports/pdfdownload",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "reports", "pdfdownload"]
            },
            description: "Downloads or streams the generated PDF report for a specimen."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "let rawBody     = pm.request.body && pm.request.body.mode === 'raw' ? pm.request.body.raw : '';",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 200', () => pm.response.to.have.status(200));",
                  "pm.test('Content-Type PDF or JSON', function() {",
                  "  const ct = pm.response.headers.get('Content-Type') || '';",
                  "  pm.expect(ct).to.satisfy(v => v.includes('pdf') || v.includes('json'));",
                  "});"
                ]
              }
            }
          ]
        },
        {
          id: "req-10",
          name: "ReportRegeneration",
          request: {
            method: "POST",
            header: [
              { key: "Content-Type", value: "application/json" },
              { key: "X-App-Key", value: "{{hmacAppKey}}" },
              { key: "X-Timestamp", value: "{{hmac_timestamp}}" },
              { key: "X-Nonce", value: "{{hmac_nonce}}" },
              { key: "X-Signature", value: "{{hmac_signature}}" }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({ SpecimenIds: ["DR08052601"] }, null, 2)
            },
            url: {
              raw: "{{baseUrl}}/api/v1/Reporting/regenerate",
              host: ["{{baseUrl}}"],
              path: ["api", "v1", "Reporting", "regenerate"]
            },
            description: "Triggers regeneration for given specimen IDs."
          },
          event: [
            {
              listen: "prerequest",
              script: {
                exec: [
                  "const appKey    = pm.collectionVariables.get('hmacAppKey');",
                  "const secret    = pm.collectionVariables.get('hmacSecret');",
                  "const timestamp = Math.floor(Date.now() / 1000).toString();",
                  "const nonce     = pm.variables.replaceIn('{{$guid}}');",
                  "const method    = pm.request.method.toUpperCase();",
                  "const url       = pm.request.url.getPathWithQuery();",
                  "let rawBody     = pm.request.body && pm.request.body.mode === 'raw' ? pm.request.body.raw : '';",
                  "const bodyMd5   = CryptoJS.MD5(rawBody).toString().toLowerCase();",
                  "const canonical = [method, url, timestamp, nonce, bodyMd5].join('\\n');",
                  "const signature = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Base64);",
                  "pm.variables.set('hmac_timestamp', timestamp);",
                  "pm.variables.set('hmac_nonce', nonce);",
                  "pm.variables.set('hmac_signature', signature);",
                  "pm.request.headers.upsert({ key: 'X-App-Key',   value: appKey });",
                  "pm.request.headers.upsert({ key: 'X-Timestamp', value: timestamp });",
                  "pm.request.headers.upsert({ key: 'X-Nonce',     value: nonce });",
                  "pm.request.headers.upsert({ key: 'X-Signature', value: signature });"
                ]
              }
            },
            {
              listen: "test",
              script: {
                exec: [
                  "pm.test('Status 200', () => pm.response.to.have.status(200));",
                  "pm.test('Content-Type PDF or JSON', function() {",
                  "  const ct = pm.response.headers.get('Content-Type') || '';",
                  "  pm.expect(ct).to.satisfy(v => v.includes('pdf') || v.includes('json'));",
                  "});"
                ]
              }
            }
          ]
        }
      ]
    }
  ]
};
